import type { MenuItem } from '@/types'

export const MENU: MenuItem[] = [
  // Drinks
  {
    id: 'banana-milk-coffee',
    name: 'Banana Milk Coffee Latte',
    description: 'Espresso and banana milk latte with a drizzle of caramel',
    price: 4.00,
    category: 'Drinks',
    emoji: '🍌',
    calories: 180,
    allergens: ['dairy', 'soy'],
    ingredients: ['espresso', 'banana milk', 'caramel syrup', 'oat milk'],
    tempOptions: ['iced'],
    image: '/menu/banana-latte.jpeg',
  },
  {
    id: 'hojicha-persimmon',
    name: 'Hojicha Persimmon Latte',
    description: 'Roasted hojicha latte with persimmon purée and oat milk',
    price: 4.00,
    category: 'Drinks',
    emoji: '🍂',
    calories: 150,
    allergens: ['soy'],
    ingredients: ['roasted hojicha', 'persimmon purée', 'oat milk', 'honey'],
    tempOptions: ['iced'],
    image: '/menu/hojicha-persimmon.jpeg',
  },
  {
    id: 'matcha-yuzuade',
    name: 'Matcha Yuzuade',
    description: 'Ceremonial matcha with bright yuzu and sparkling water',
    price: 4.00,
    category: 'Drinks',
    emoji: '🍋',
    calories: 80,
    allergens: [],
    ingredients: ['ceremonial matcha', 'yuzu juice', 'sparkling water', 'honey'],
    tempOptions: ['iced'],
    image: '/menu/matcha-yuzuade.jpg',
    addOns: ['matcha'],
  },
  {
    id: 'lychee-matcha',
    name: 'Matcha Latte w/ Lychee Whipped Cream',
    description: 'Smooth ceremonial matcha latte topped with airy lychee whipped cream',
    price: 4.00,
    category: 'Drinks',
    emoji: '🌸',
    calories: 170,
    allergens: ['soy', 'dairy'],
    ingredients: ['ceremonial matcha', 'oat milk', 'heavy cream', 'lychee juice'],
    tempOptions: ['hot', 'iced'],
    image: '/menu/lychee-matcha.jpg',
  },
  {
    id: 'coffee-latte',
    name: 'Coffee Latte',
    description: 'Classic espresso latte, rich and smooth',
    price: 4.00,
    category: 'Drinks',
    emoji: '☕',
    calories: 140,
    allergens: ['dairy', 'soy'],
    ingredients: ['espresso', 'oat milk'],
    tempOptions: ['hot'],
    image: '/menu/coffee-latte.jpeg',
    imagePosition: 'center 50%',
    addOns: ['strawberry'],
  },
  // Food
  {
    id: 'scallion-pancake-croissant',
    name: 'Scallion Pancake Croissant',
    description: 'Flaky croissant layered with savory scallion pancake',
    price: 2.50,
    category: 'Food',
    emoji: '🥐',
    calories: 320,
    allergens: ['gluten', 'eggs', 'dairy'],
    ingredients: ['all-purpose flour', 'butter', 'eggs', 'scallions', 'sesame oil', 'salt'],
  },
  {
    id: 'jasmine-grape-cake',
    name: 'Jasmine Green Grape Cream Cake',
    description: 'Jasmine tea sponge layered with green grapes and diplomat cream',
    price: 2.50,
    category: 'Food',
    emoji: '🍰',
    calories: 280,
    allergens: ['gluten', 'eggs', 'dairy'],
    ingredients: ['jasmine sponge cake', 'green grapes', 'diplomat cream', 'heavy cream', 'jasmine tea'],
    image: '/menu/grape-cake.jpeg',
    imagePosition: 'center 75%',
  },
  {
    id: 'strawberry-earl-grey-cookies',
    name: 'Strawberry & Earl Grey Cookies',
    description: 'Buttery shortbread with earl grey and a swirl of strawberry jam',
    price: 2.50,
    category: 'Food',
    emoji: '🍓',
    calories: 140,
    allergens: ['gluten', 'dairy'],
    ingredients: ['butter', 'all-purpose flour', 'earl grey tea', 'strawberry jam', 'powdered sugar'],
    image: '/menu/strawberry-earlgrey.jpeg',
    imagePosition: 'center 60%',
  },
  {
    id: 'black-sesame-coconut-cookies',
    name: 'Black Sesame Coconut Cookies',
    description: 'Crispy cookies with toasted black sesame and coconut flakes',
    price: 2.50,
    category: 'Food',
    emoji: '🍪',
    calories: 160,
    allergens: ['gluten', 'tree nuts'],
    ingredients: ['black sesame paste', 'coconut flakes', 'butter', 'flour', 'sugar', 'vanilla'],
  },
]

export const CATEGORIES = [...new Set(MENU.map(item => item.category))]
