import type { MenuItem } from '@/types'

export const MENU: MenuItem[] = [
  // Drinks
  {
    id: 'banana-milk-coffee',
    name: 'Banana Milk Coffee Latte',
    description: 'Espresso over 바나나맛 우유, made with real banana',
    price: 8.50,
    category: 'Drinks',
    emoji: '🍌',
    calories: 180,
    allergens: ['dairy', 'soy'],
    ingredients: ['espresso', 'banana milk', 'banana'],
    tempOptions: ['iced'],
    milkOptions: ['Banana Milk'],
    image: '/menu/banana-latte.jpeg',
  },
  {
    id: 'hojicha-persimmon',
    name: 'Hojicha Persimmon Latte',
    description: 'Hojicha (roasted matcha) over persimmon compote',
    price: 8.50,
    category: 'Drinks',
    emoji: '🍂',
    calories: 150,
    allergens: ['soy', 'dairy'],
    ingredients: ['hojicha', 'milk', 'persimmon'],
    tempOptions: ['iced'],
    milkOptions: ['Fairlife', 'Oat Milk'],
    image: '/menu/hojicha-persimmon.jpeg',
  },
  {
    id: 'matcha-yuzuade',
    name: 'Yuzuade',
    description: 'Yuzuco Yuzu Juice, sugar, and water with optional shot of matcha. Bright, tart and refreshing.',
    price: 8.50,
    category: 'Drinks',
    emoji: '🍋',
    calories: 80,
    allergens: [],
    ingredients: ['ceremonial matcha', 'yuzu juice', 'sparkling water', 'honey'],
    tempOptions: ['iced'],
    image: '/menu/yuzuade.jpg',
    addOns: ['matcha'],
  },
  {
    id: 'lychee-matcha',
    name: 'Matcha Latte w/ Lychee Whipped Cream',
    description: 'Smooth ceremonial matcha latte topped with airy lychee whipped cream',
    price: 8.50,
    category: 'Drinks',
    emoji: '🌸',
    calories: 170,
    allergens: ['soy', 'dairy'],
    ingredients: ['ceremonial matcha', 'oat milk', 'heavy cream', 'lychee juice'],
    tempOptions: ['hot', 'iced'],
    milkOptions: ['Fairlife', 'Oat Milk'],
    image: '/menu/lychee-matcha.JPG',
    imageTransform: 'translateY(-7%)',
  },
  {
    id: 'coffee-latte',
    name: 'Coffee Latte',
    description: 'Hot latte with option of adding emulsified strawberry syrup',
    price: 4.00,
    category: 'Drinks',
    emoji: '☕',
    calories: 140,
    allergens: ['dairy', 'soy'],
    ingredients: ['espresso', 'milk', 'strawberry'],
    tempOptions: ['hot'],
    milkOptions: ['Fairlife', 'Oat Milk'],
    image: '/menu/coffee-latte.jpeg',
    imagePosition: 'center 50%',
    addOns: ['strawberry'],
  },
  {
    id: 'blueberry-coffee-latte',
    name: 'Blueberry Coffee Latte',
    description: 'Espresso and milk over house-made blueberry compote',
    price: 7.50,
    category: 'Drinks',
    emoji: '🫐',
    calories: 190,
    allergens: ['dairy'],
    ingredients: ['espresso', 'milk', 'blueberry'],
    tempOptions: ['iced'],
    milkOptions: ['Fairlife', 'Oat Milk'],
    image: '/menu/blueberry-coffee-latte.webp',
  },
  // Food
  {
    id: 'scallion-pancake-croissant',
    name: 'Scallion Pancake Pastry Rolls',
    description: 'Flaky puff pastry layered with scallions, sesame oil, and white pepper powder',
    price: 6.50,
    category: 'Food',
    emoji: '🥐',
    calories: 320,
    allergens: ['gluten', 'eggs', 'dairy'],
    ingredients: ['all-purpose flour', 'butter', 'eggs', 'scallions', 'sesame oil', 'salt'],
    image: '/menu/green-onion-crossinat.JPG',
    imageTransform: 'translateY(-12%)',
  },
  {
    id: 'jasmine-grape-cake',
    name: 'Jasmine Green Grape Cream Cake',
    description: 'Vanilla & jasmine tea sponge, layered with jasmine tea-infused custard and green grapes; chantilly cream exterior',
    price: 6.50,
    category: 'Food',
    emoji: '🍰',
    calories: 280,
    allergens: ['gluten', 'eggs', 'dairy'],
    ingredients: ['egg', 'neutral oil', 'cake flour', 'jasmine tea', 'heavy cream', 'vanilla bean', 'green grape'],
    image: '/menu/grape-cake.jpeg',
  },
  {
    id: 'strawberry-earl-grey-cookies',
    name: 'Strawberry & Earl Grey Cookies',
    description: 'Neapolitan-style cookie with tri-flavor of: vanilla bean, strawberry, and black tea (mix of earl and victoria grey)',
    price: 2.50,
    category: 'Food',
    emoji: '🍓',
    calories: 140,
    allergens: ['gluten', 'dairy', 'eggs'],
    ingredients: ['butter', 'flour', 'egg', 'sugar', 'strawberry', 'black tea', 'dehydrated strawberry'],
    image: '/menu/strawberry-earlgrey.jpeg',
    imagePosition: 'center 60%',
  },
  {
    id: 'black-sesame-coconut-cookies',
    name: 'Susuwatari Cookies',
    description: 'Crispy coconut flake cookies with a rich sweetened black sesame paste — dark, nutty, and a little magical.',
    price: 2.50,
    category: 'Food',
    emoji: '🍪',
    calories: 160,
    allergens: ['gluten', 'tree nuts'],
    ingredients: ['black sesame paste', 'coconut flakes', 'butter', 'flour', 'sugar', 'vanilla'],
    image: '/menu/black-sesame-cookie.JPG',
    imageTransform: 'translateY(-15%)',
  },
  {
    id: 'cherry-almond-tart',
    name: 'Cherry Almond Tart',
    description: 'Buttery tart shell filled with almond frangipane and cherries',
    price: 6.00,
    category: 'Food',
    emoji: '🍒',
    calories: 300,
    allergens: ['gluten', 'tree nuts', 'dairy', 'eggs'],
    ingredients: ['flour', 'butter', 'almond', 'cherry', 'egg', 'sugar'],
    image: '/menu/cherry-almond-tart.webp',
  },
  {
    id: 'watermelon-lychee-sorbet',
    name: 'Watermelon Lychee Sorbet',
    description: 'Refreshing frozen sorbet of watermelon and lychee',
    price: 4.00,
    category: 'Food',
    emoji: '🍉',
    calories: 120,
    allergens: [],
    ingredients: ['watermelon', 'lychee', 'sugar'],
    image: '/menu/watermelon-lychee-sorbet.webp',
  },
]

export const CATEGORIES = [...new Set(MENU.map(item => item.category))]
